### ISSUE TITLE
Is the build from harbour outdated?

### ISSUE THREAD

**Issue by KyeNormanGill** [RestoreMonarchyPlugins/AirdropManager#2]
I'm using the build from harbor. https://harbor.rocketmod.net/plugins/airdropmanager/

When it generates the configuration file all i get is, 
```xml
<?xml version="1.0" encoding="utf-8"?>
<AirdropManagerConfiguration xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Airdrops>
    <Airdrop>
      <Name>Assault</Name>
      <Items>
        <id>33335</id>
        <id>1379</id>
        <id>1381</id>
        <id>1381</id>
        <id>1381</id>
        <id>119</id>
        <id>119</id>
	<id>146</id>
        <id>119</id>
        <id>151</id>
      </Items>
    </Airdrop>
  </Airdrops>
</AirdropManagerConfiguration>
```

Looking at the source, there should be alot more configuration settings right?

**Comment by RestoreMonarchy** [comment]
The plugin is being re-made because it was broke after Unturned update 2 weeks ago. So far remaking it I only made this feature. For this newest build source code you can check the master branch is not set by default yet (will change it later).

**Comment by RestoreMonarchy** [comment]
The AirdropManager 2.1 has now all the AirdropManager 2.0 features and got the bugs fixed + some improvements. 
Available on Rocket Harbor: https://harbor.rocketmod.net/plugins/airdropmanager/
